# Generated by Django 2.2 on 2019-08-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColaboraApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nomeDepartamento',
            field=models.CharField(max_length=50),
        ),
    ]
